### ISSUE TITLE
Missing or unsupported mandatory dependencies

### ISSUE THREAD

**Issue by RuDas-KR** [Frinn38/Custom-Machinery-Mekanism#1]
MC Ver         : 1.18.2
Forge Ver     : 40.2.2
Java Ver        : Azul Zulu 17.0.7
Create Ver    :  0.5.0.i
Flywheel Ver : 0.6.8.a

[main/ERROR] [ne.mi.fm.lo.ModSorter/LOADING]: Missing or unsupported mandatory dependencies:

Mod ID: 'create', Requested by: 'custommachinerycreate', Expected range: '[0.5.0.i-249,)', Actual version: '0.5.0.i'
Exception in thread "main" java.lang.module.ResolutionException: Modules krypton and pluto export package com.velocitypowered.natives.util to module coalexplosion
at java.base/java.lang.module.Resolver.resolveFail(Resolver.java:901)
at java.base/java.lang.module.Resolver.failTwoSuppliers(Resolver.java:815)
at java.base/java.lang.module.Resolver.checkExportSuppliers(Resolver.java:736)
at java.base/java.lang.module.Resolver.finish(Resolver.java:380)
at java.base/java.lang.module.Configuration.<init>(Configuration.java:140)
at java.base/java.lang.module.Configuration.resolveAndBind(Configuration.java:494)
at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.ModuleLayerHandler.buildLayer(ModuleLayerHandler.java:70)
at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.TransformationServicesHandler.buildTransformingClassLoader(TransformationServicesHandler.java:60)
at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.Launcher.run(Launcher.java:104)
at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
at cpw.mods.bootstraplauncher@1.0.0/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149)

**Comment by Frinn38** [comment]
Indeed I messed up the dependencies, should be fixed now, but note that this addon can't be used currently as it requires an update of Custom Machinery to work (CM-1.18.2-0.8.3). Don't worry that update will come soon.
Also CM Create now has its own github with issue tracker, for the future use [this](https://github.com/Frinn38/Custom-Machinery-Create/issues) page instead of here.
